### ISSUE TITLE
Make alert trigger pattern configurable

### ISSUE THREAD

**Issue by niccs** [PanicInitiative/PanicButton#139]
Allow the user to change the trigger code.

Change trigger pattern:--
Number of first clicks (default is 4)
Guard time duration (currently 2 seconds)
Number of confirmation clicks (default is 1)

After changing the Haptic Feedback option the user should be offered to do the trigger exercise again.

**Comment by niccs** [comment]
Kindly have a look in my understanding:--

As per the current code in dev branch trigger pattern is: and only following first three parameters will be configurable, as per #139 issue:--

Initial Clicks:-5
Guard time= 3 sec
Confirmation clicks is:1

Other parameters:--
Haptic feedback vibration duration :-- 2 sec
Confirmation of alert trigger vibration duration is = 0.5 sec

1)	User pressed 5 initial clicks <= 6 sec(this 6 sec time is non configurable)
2)	Haptic feedback vibration plays for 2 sec -- any click during this time will be ignored
3)	Guard time is 3 sec (So user should press confirmation click with in the 3 secs of guard time)

So the queries are:--
If we are making the confirmation clicks configurable—the logic should be added to handle it. 
a)	What is the maximum number of confirmation clicks.
b)	Just like the 5 initial clicks should be with in 6 sec time limit(point 1 above), what should be the time limit for confirmation clicks.
c)	We need Advanced settings page for this—with header as:
"Change trigger Pattern: " and then text boxes as--

Number of first clicks(default is 5)—
Guard Time duration(default is 3 sec)--
Number of confirmation clicks(defaults is 1)--

**Comment by jmatsushita** [comment]
Hi @niccs 

Thanks for the analysis. Let's not make the number of confirmation clicks configurable for now.

I realise with what you reminded me here, that I've used guard time the wrong way (I thought it was the time between the last initial click and the moment where you can enter the confirmation click. Also I realise how indeed both trigger pattern and vibration are related So I suggest we merge the too issues into this one and the following approach:

### Advanced Settings
#### Trigger Settings

##### Pattern

 - Initial Presses (Number of presses needed to trigger the alarm. Increasing the number of initial presses can help reduce false alarms. Also note that some devices might not detect the first press.)

    4 presses / (default) 5 presses  / 6 presses / 7 presses

 - Initial Time (Time to complete the number of initial presses. Decreasing this number might create problems with detecting multiple presses with certain devices.)

   4 sec / 5 sec / (default) 6 sec / 7 sec / 8 sec

 - Confirmation Wait Time (Time to wait until the confirmation press. This wait will help avoid false alarms. You can try to augment it if you experience false alarms.)

    1 sec / (default) 2 sec / 3 sec / 4 sec

##### Vibration

 - Confirmation Wait Vibration (Vibration pattern during the wait time until the confirmation press).
    (X) (default) Vibrate Continuously
    (  ) Vibrate Every Second

 - Alarm Sending Confirmation (Vibration pattern to confirm the alarm has been activated. Choosing a recognisable pattern can help you be reassured that the alert has been sent, or identify better potential false alarms).
    (X) (default) Long Vibration
    (  ) Repeated Short Vibrations
    (  ) Three short - pause - Three short
    (  ) SOS: Three short - Three long - Three short
    (  ) None

  [ Cancel ]   [ Test and Save ]   [ Save without Testing ] (-> Warning "You have changed the trigger pattern and have chosen not to test your new settings. Are you sure you want to continue? [ Go back and Test ] [ Continue without Testing ]

-----

Further to your other questions on #140 
 - Yes the settings are radio buttons for all and maybe a window similar to the one in the [alert settings](https://github.com/PanicInitiative/PanicButton/blob/master/src/main/java/org/iilab/pb/fragment/MainSetupAlertFragment.java#L164-L171)
 - For the vibration durations, please try them on your device and see what seems to work. We can adjust after that.
 - Let's have all the warnings use the same code as the dialog displayed when the user goes to Settings > Restart the Installation. Which is coded in this [fragment](https://github.com/PanicInitiative/PanicButton/blob/master/src/main/java/org/iilab/pb/fragment/WarningFragment.java), linked to from the settings in [this way](https://github.com/PanicInitiative/PanicButton/blob/master/assets/mobile_en.json#L493-L494) and with the Text and Action buttons defined [here](https://github.com/PanicInitiative/PanicButton/blob/master/assets/mobile_en.json#L353-L363. this code might need to be modified in order to allow multiple Actions.
 - Yes let's show the warnings as soon as the user select the option.
 - Offering the user to redo the exercise should be (in theory) as simple as linking the "Save and Test" button to a copy of [these 3 objects in the json](https://github.com/PanicInitiative/PanicButton/blob/master/assets/mobile_en.json#L228-L273) with different names and changing the logic of returning to the home dialog or back to the settings. I'm sure you can figure this out.
 - Good point about the Animation. For now let's not display the image, and instead display a summary of the settings in text such as "Press {{ initial_presses }} times, then wait {{ wait_time }} seconds, and press once more to confirm.". Making the text in the JSON dynamic like this might not be so straightforward so, I'm ok with releasing a test version with only this static text "Press the number of times you have configured, wait for the number of seconds you have configured, and press once more to confirm".

Hopefully that covers everything!

**Comment by niccs** [comment]
@jmatsushita: 
Your post clear most of the things, adding few more points, please have a look:

Confirmation Wait Time:-- Currently its 2 sec and during this 2 secs we have a a full 2 sec long vibration. So the options 3sec/4sec continues long vibrations would be too long.

Confirmation Wait Vibration:- You can see, this is closely linked to  Confirmation Wait Time option above —So following are the possible combinations of the use cases as per my understanding:

Case 1)—If confirmation wait time is 3 sec, we have one long vibration for 3 sec
Case 2)—If confirmation wait time is 2 sec, we have one long vibration for 2 sec
Case  3)- If confirmation wait time is 1 sec, we have one long vibration for 1 sec

Case  4)—If confirmation wait time is 3 sec, vibrate every second (.5 sec vibrate + .5 sec pause)—repeated 3 times( to complete the confirmation wait time of 3 secs)
Case 5 )—If confirmation wait time is 2 sec, vibrate every second (.5 sec vibrate + .5 sec pause)—repeated 2 times ( to complete the confirmation wait time of 2 secs)
Case 6)—If confirmation wait time is 1 sec, vibrate every second (.5 sec vibrate + .5 sec pause)—no repetition


Also I feel, making  Initial  time configurable would be too much technical for end users to understand. As this option is closely linked with Initial clicks. So for example, if user selects 7 initial clicks within  4 sec initial time(the SCREEN_ON and SCREEN_OFF broadcast (7 times in 4 secs) is not feasible. Also the other way around, 4 clicks in 7 secs—in this case there will be more chances of missed/skipped clicks, as the confirmation vibration will only start after  the end of 7 secs.

So, instead of making Initial time configurable for users, we can adjust in code, like the way done now. If there are 5 initial clicks the time is 6 sec, If user selects 4 initial clicks—we can assign 5 sec and if user selects 7 initial clicks we can assign 8 sec.

Just my personal view point:-

Alarm NOT Confirmed:--  (default none), I feel this is the best option. Making it configurable will create confusions between “confirmation vibration pattern “ and  “alarm not configured”pattern.  In hazard situation, it would be tough, keeping track of understanding vibration patterns.

I feel, the less options we give to end users, it will be easier for them to remember, what they have configured. 

Please let me know your view points on my understanding.

**Comment by niccs** [comment]
Offering the user to redo the exercise should be (in theory) as simple as linking the "Save and Test" button to a copy of these 3 objects in the json with different names and changing the logic of returning to the home dialog or back to the settings. --

I have added the test button in Advanced settings – in order, to execute the re-do of training exercise. Right now its not in working state.

Technical Issues: -- If we go by design of PB app, the redo exercise ideally should be as simple as re-configuring the 3 json objects you mentioned above. But looking into the code, there are various workarounds done earlier.

For instance, if you see the existing Wizard activity’s onResume() and onPause(), there are json objects hardcoded to handle the activities pause and resume functionalities. 

Another related class in PageActionAdapter, where also you can see cases based on some json objects. I am analysing these, where all new additions and  can affect  the existing pause-resume workflow.

FYI--This above mentioned issue is related to #138 (communication between activities and fragment). Since this communication is not handled properly the pause and resume of all activity classes are flooded with possible workarounds.

**Comment by niccs** [comment]
@jmatsushita , For redo training exercise part, I have copied the existing related training pages , as we do while installing the app for the first time. We need to review and re-write(in all languages) those related pages text.
