### ISSUE TITLE
Improve performance of initial content loading.

### ISSUE THREAD

**Issue by jmatsushita** [PanicInitiative/PanicButton#75]
Looking at the code that loads the content on installation, it would be more efficient if we installed only english and trigger edthe other language installs when the user switches language.

**Comment by niccs** [comment]
@jmatsushita, if we are planning to refactor code to remove SQLlite DB and json files,  this issue will be indirectly fixed.  Please let me know the priority to have the refactoring done.

**Comment by niccs** [comment]
@jmatsushita, Since we are not refactoring the code, so to improve performance of initial loading of the application following is done:-

1) On first time installation, only the user device OS language data is parsed into content DB, if the app doesnt support the language, then English mobile data and help data is loaded.
2) From Wizard Menu and from settings menu, if the user changes the language selection, that particular language data is parsed and stored.
3)One more existing use case is:-- If the mobile data version for English language is changed(in json), then the OS specific language data parsing is triggered( as per point -1 aboive)

Kindly let me know, if there is any other use case, to be considered.
