### ISSUE TITLE
Add button to disable Power Button trigger

### ISSUE THREAD

**Issue by jmatsushita** [PanicInitiative/PanicButton#80]
Add a button to disable the power button.

**Comment by niccs** [comment]
from @jmatsushita ;

One new think I'd like you to look at is the possibility to add a button on the main page (home-configured with the Disguise button) to Toggle the alert on and off. Can you add a task in the current iteration to look at this and let me know if you think you can make progress on this?

**Comment by niccs** [comment]
@jmatshushita:

Just to clarify my understanding for the requirement:
We can trigger alert by two ways-- Using Power button , and using Apps's disguise screen.

1) On "home-ready disguise " screen, we are looking for adding another button, whose purpose will be to enable/disable the trigger of alarm from only the Power button press (and not from the apps's disguise screen). My understanding is, this is to stop the false triggers from power button manually. Otherwise, in case we are disabling the alert completely both ways(power button and disguise screen) the app's purpose is lost

2) If my understanding is correct, then we can add a checkbox in "Settings-- alert Settings" with caption something as " Power button trigger enabled --" which can turn on/off the Power button trigger.

Please comment.

**Comment by jmatsushita** [comment]
@niccs Your understanding is correct, except please add the checkbox directly below the "Disguise" button.

**Comment by niccs** [comment]
From @jmatsushita,
Include in the Advanced Settings as "Deactivate Power Button Trigger". Maybe as a Radio Select with:

(*) Activated (default)
( ) Deactivated
( ) Debug Mode

When the Deactivated or Debug Mode is deactivated add a Notification such as "The Panic Button Power Button Trigger is deactivated." as an icon and on the lock screen.

**Comment by niccs** [comment]
Currently  I have added code in Disguise screen and checked in the code.. so that i can start working on trigger patterns(just to avoid merge conflicts). Also  for moving to Advanced settings , it requires a new screen to be developed, which is time consuming. meanwhile logic part is working and its tested, so till the time, new screen is developed, i will hide the views from disguise screen. 
Also notification part needs to be worked on

**Comment by jmatsushita** [comment]
Maybe in the future we can change our approach to building fragments dynamically but for now let's use the current dynamic fragment appraoch.

 In other words, you need to add an item in the items array in the "settings" object in the mobile_en.json file : https://github.com/PanicInitiative/PanicButton/blob/master/assets/mobile_en.json#L467-L495  

Then you can create an entry similar to this one for the Alert frequency: https://github.com/PanicInitiative/PanicButton/blob/master/assets/mobile_en.json#L451-L464

Which connects to this Fragment: https://github.com/PanicInitiative/PanicButton/blob/master/src/main/java/org/iilab/pb/fragment/MainSetupAlertFragment.java

Which is called from the MainActivity here: https://github.com/PanicInitiative/PanicButton/blob/master/src/main/java/org/iilab/pb/MainActivity.java#L127-L128

**Comment by niccs** [comment]
I think , I was not clear in my suggestion:-
Adding the Advanced Settings  new screen in PB app will be in line with the existing screens are added, the way you discussed(vioa json and MainActivity). There is no change there.
But we need to design the new layout of Advanced Settings page plus a new interactive fragment to handle that, which is time consuming. My view point was to use the Settings framework of Android for this Advanced Settings screen. The purpose of Advanced setting screen is to store the configurations in application preferences (application context), which is what this framework is used for.
Benefits will be—
1)	We can develop the Advanced setting screen faster, with the settings framework taking care of all UI related things .
2)	The new interactive fragment to handle and store the UI settings will again be very quick to develop.
3)	It will be inline with Android Settings guidelines.
4)	It has in-built features of radiobuttons groups(which can be used for #80), textboxes(which can be used for (#139).
5)	In future, adding new settings will be much easier.
Challange:--
1)	Except changing the minimum sdk version from 10 to 11, I don’t see any need in developing a new view UI for advanced settings.

We can use this to make the Advanced settings screen and then blend it in MainActivity, as done with other screen, its just the way the screen is designed.

**Comment by niccs** [comment]
@jmatsushita , Need more information on notification part.

When the power button alarm is disabled, a notification with text "the power button trigger is deactivated" will come. 
Is there any action associated with this notification:--
Now, when the user clicks this notification
1) He is directed to Advanced settings screen??  or
2) No Action.

**Comment by jmatsushita** [comment]
@jimmylogan says in #175

This is the first option that is being given to the user to configure the trigger. However, this is the least preferable option in terms of limiting the app’s usefulness; it would be better to encourage them to try configuring the trigger in different ways as a way of addressing ‘false trigger’ incidents. 

I suggest we move the option to deactivate the power button trigger further down the menu (after the ‘REDO TRAINING’ option) in order that the user sees that there are other ways to address the issue.

**Comment by jmatsushita** [comment]
@niccs Yes please 1) seems like the best option.

Also can you clarify if you ended up needing to change the minimum sdk version? If so does this mean we have removed support for older versions of android?
